-- Add positions to an existing PocketLedger database.
-- Does not drop categories, budgets, debts, or transactions.
-- Safe to run once. Running it again fails on objects that already exist.

create type public.position_kind as enum ('sip', 'fd', 'savings', 'emergency');

create table public.position (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  name text not null,
  kind public.position_kind not null,
  notes text,
  monthly_amount numeric(14, 2),
  market_value numeric(14, 2),
  valued_on date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint position_name_not_blank check (length(btrim(name)) > 0),
  constraint position_monthly_amount_positive check (monthly_amount is null or monthly_amount > 0),
  constraint position_market_value_nonnegative check (market_value is null or market_value >= 0),
  constraint position_value_has_date check (
    (market_value is null and valued_on is null)
    or (market_value is not null and valued_on is not null)
  )
);

create index position_user_id_kind_idx on public.position (user_id, kind);

alter table public.transaction
  add column position_id bigint references public.position (id) on delete restrict;

alter table public.transaction drop constraint transaction_one_subject;

alter table public.transaction
  add constraint transaction_one_subject check (
    num_nonnulls(category_id, debt_id, position_id) = 1
  );

create index transaction_position_id_idx on public.transaction (position_id);

create or replace function public.position_normalize()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.name := btrim(new.name);
  if new.notes is not null then
    new.notes := nullif(btrim(new.notes), '');
  end if;
  return new;
end;
$$;

create or replace function public.transaction_validate()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  category_user uuid;
  category_kind public.category_type;
  debt_user uuid;
  position_user uuid;
begin
  if new.description is not null then
    new.description := nullif(btrim(new.description), '');
  end if;

  if new.category_id is not null then
    select user_id, category_type
    into category_user, category_kind
    from public.categories
    where id = new.category_id;

    if category_user is null or category_user is distinct from new.user_id then
      raise exception 'Transaction category must belong to the same user';
    end if;

    if category_kind = 'income' and new.direction <> 'inflow' then
      raise exception 'Income categories only accept inflow transactions';
    end if;

    if category_kind = 'expense' and new.direction <> 'outflow' then
      raise exception 'Expense categories only accept outflow transactions';
    end if;
  end if;

  if new.debt_id is not null then
    select user_id into debt_user
    from public.debt
    where id = new.debt_id;

    if debt_user is null or debt_user is distinct from new.user_id then
      raise exception 'Transaction debt must belong to the same user';
    end if;
  end if;

  if new.position_id is not null then
    select user_id into position_user
    from public.position
    where id = new.position_id;

    if position_user is null or position_user is distinct from new.user_id then
      raise exception 'Transaction position must belong to the same user';
    end if;
  end if;

  return new;
end;
$$;

create or replace function public.position_owned_by_current_user(target_id bigint)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.position
    where id = target_id
      and user_id = (select auth.uid())
  );
$$;

create trigger position_normalize
  before insert or update on public.position
  for each row execute function public.position_normalize();

create trigger position_touch_updated_at
  before insert or update on public.position
  for each row execute function public.touch_updated_at();

create trigger position_reject_user_change
  before update on public.position
  for each row execute function public.reject_user_id_change();

drop view if exists public.transactions_with_ref;

create view public.transactions_with_ref
with (security_invoker = true) as
select
  t.id as transaction_id,
  t.user_id,
  t.amount,
  t.direction,
  t.transaction_date,
  t.description,
  t.category_id,
  c.category_name,
  c.category_type,
  c.parent_category as parent_category_id,
  t.debt_id,
  d.counterparty,
  d.debt_type,
  t.position_id,
  p.name as position_name,
  p.kind as position_kind,
  case
    when t.debt_id is not null then 'debt'
    when t.position_id is not null then 'position'
    else 'category'
  end as transaction_type,
  nullif(
    concat_ws(' ', t.description, c.category_name, d.counterparty, p.name),
    ''
  ) as search_text
from public.transaction as t
left join public.categories as c on c.id = t.category_id
left join public.debt as d on d.id = t.debt_id
left join public.position as p on p.id = t.position_id;

revoke all on function public.position_normalize() from public, anon, authenticated;
revoke all on function public.transaction_validate() from public, anon, authenticated;
revoke all on function public.position_owned_by_current_user(bigint) from public, anon;

grant execute on function public.position_owned_by_current_user(bigint) to authenticated;

alter table public.position enable row level security;
alter table public.position force row level security;

create policy "position_select_own"
  on public.position
  for select
  to authenticated
  using (user_id = (select auth.uid()));

create policy "position_insert_own"
  on public.position
  for insert
  to authenticated
  with check (user_id = (select auth.uid()));

create policy "position_update_own"
  on public.position
  for update
  to authenticated
  using (user_id = (select auth.uid()))
  with check (user_id = (select auth.uid()));

create policy "position_delete_own"
  on public.position
  for delete
  to authenticated
  using (user_id = (select auth.uid()));

drop policy if exists "transaction_insert_own" on public.transaction;
drop policy if exists "transaction_update_own" on public.transaction;

create policy "transaction_insert_own"
  on public.transaction
  for insert
  to authenticated
  with check (
    user_id = (select auth.uid())
    and (
      (
        category_id is not null
        and debt_id is null
        and position_id is null
        and public.category_owned_by_current_user(category_id)
      )
      or (
        debt_id is not null
        and category_id is null
        and position_id is null
        and public.debt_owned_by_current_user(debt_id)
      )
      or (
        position_id is not null
        and category_id is null
        and debt_id is null
        and public.position_owned_by_current_user(position_id)
      )
    )
  );

create policy "transaction_update_own"
  on public.transaction
  for update
  to authenticated
  using (user_id = (select auth.uid()))
  with check (
    user_id = (select auth.uid())
    and (
      (
        category_id is not null
        and debt_id is null
        and position_id is null
        and public.category_owned_by_current_user(category_id)
      )
      or (
        debt_id is not null
        and category_id is null
        and position_id is null
        and public.debt_owned_by_current_user(debt_id)
      )
      or (
        position_id is not null
        and category_id is null
        and debt_id is null
        and public.position_owned_by_current_user(position_id)
      )
    )
  );

revoke all on table public.position from public, anon;
revoke all on table public.transactions_with_ref from public, anon;

grant select, insert, update, delete on table public.position to authenticated;
grant select on table public.transactions_with_ref to authenticated;

grant all on table public.position to service_role;
grant select on table public.transactions_with_ref to service_role;

grant usage, select on all sequences in schema public to authenticated, service_role;
