-- PocketLedger schema.
-- Categories, budgets, debts, positions, and transactions.
-- A position is money you still own after it leaves spending: SIP, FD, savings,
-- or an emergency fund. Marks are amounts you type. There is no price feed.
--
-- This script drops and recreates the public ledger tables.
-- Run it in the Supabase SQL editor of a new project, or only when the existing
-- rows can be discarded. Auth users are not touched.

create extension if not exists btree_gist;

drop view if exists public.transactions_with_ref;
drop table if exists public.transaction;
drop table if exists public.contribution_target;
drop function if exists public.contribution_target_validate();
drop table if exists public.budget;
drop table if exists public.debt;
drop table if exists public.position;
drop table if exists public.investment;
drop table if exists public.categories;

drop type if exists public.transaction_ref;
drop type if exists public.investment_asset_type;
drop type if exists public.position_kind;
drop type if exists public.transaction_direction;
drop type if exists public.debt_type;
drop type if exists public.category_type;

create type public.category_type as enum ('income', 'expense');
create type public.debt_type as enum ('borrowed', 'lent');
create type public.position_kind as enum ('sip', 'fd', 'savings', 'emergency');
create type public.transaction_direction as enum ('inflow', 'outflow');

-- ---------------------------------------------------------------------------
-- Tables
-- ---------------------------------------------------------------------------

create table public.categories (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  category_name text not null,
  category_type public.category_type not null,
  color text not null,
  description text,
  parent_category bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint categories_name_not_blank check (length(btrim(category_name)) > 0),
  constraint categories_color_hex check (color ~ '^#[0-9A-Fa-f]{6}$'),
  constraint categories_not_self_parent check (parent_category is distinct from id),
  constraint categories_parent_category_fkey
    foreign key (parent_category) references public.categories (id) on delete cascade
);

create unique index categories_name_unique
  on public.categories (user_id, parent_category, lower(category_name))
  nulls not distinct;

create table public.budget (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  category_id bigint not null references public.categories (id) on delete cascade,
  amount numeric(14, 2) not null,
  start_date date not null,
  end_date date not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint budget_amount_positive check (amount > 0),
  constraint budget_date_range check (start_date <= end_date),
  constraint budget_no_overlap exclude using gist (
    user_id with =,
    category_id with =,
    daterange(start_date, end_date, '[]') with &&
  )
);

create table public.debt (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  counterparty text not null,
  debt_type public.debt_type not null,
  principal numeric(14, 2) not null,
  start_date date not null,
  due_date date,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint debt_counterparty_not_blank check (length(btrim(counterparty)) > 0),
  constraint debt_principal_positive check (principal > 0),
  constraint debt_due_after_start check (due_date is null or due_date >= start_date)
);

create table public.position (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  name text not null,
  kind public.position_kind not null,
  notes text,
  monthly_amount numeric(14, 2),
  market_value numeric(14, 2),
  valued_on date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint position_name_not_blank check (length(btrim(name)) > 0),
  constraint position_monthly_amount_positive check (monthly_amount is null or monthly_amount > 0),
  constraint position_market_value_nonnegative check (market_value is null or market_value >= 0),
  constraint position_value_has_date check (
    (market_value is null and valued_on is null)
    or (market_value is not null and valued_on is not null)
  )
);

create table public.transaction (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  amount numeric(14, 2) not null,
  direction public.transaction_direction not null,
  transaction_date date not null,
  description text,
  category_id bigint references public.categories (id) on delete restrict,
  debt_id bigint references public.debt (id) on delete restrict,
  position_id bigint references public.position (id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint transaction_amount_positive check (amount > 0),
  constraint transaction_one_subject check (
    num_nonnulls(category_id, debt_id, position_id) = 1
  )
);

create index categories_user_id_type_idx on public.categories (user_id, category_type);
create index categories_parent_category_idx on public.categories (parent_category);
create index budget_user_id_idx on public.budget (user_id);
create index budget_category_id_idx on public.budget (category_id);
create index debt_user_id_type_idx on public.debt (user_id, debt_type);
create index position_user_id_kind_idx on public.position (user_id, kind);
create index transaction_user_date_idx on public.transaction (user_id, transaction_date desc);
create index transaction_category_id_idx on public.transaction (category_id);
create index transaction_debt_id_idx on public.transaction (debt_id);
create index transaction_position_id_idx on public.transaction (position_id);

-- ---------------------------------------------------------------------------
-- Integrity triggers
-- These run as the function owner so they can compare ownership even when RLS
-- hides the other row. search_path is pinned so the body cannot be hijacked.
-- ---------------------------------------------------------------------------

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

create or replace function public.reject_user_id_change()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if tg_op = 'UPDATE' and new.user_id is distinct from old.user_id then
    raise exception 'user_id cannot be changed';
  end if;
  return new;
end;
$$;

create or replace function public.categories_validate()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  parent public.categories%rowtype;
begin
  new.category_name := btrim(new.category_name);

  if new.parent_category is not null then
    if exists (
      select 1 from public.categories child where child.parent_category = new.id
    ) then
      raise exception 'A category that already has children cannot become a child';
    end if;

    select * into parent
    from public.categories
    where id = new.parent_category;

    if not found or parent.user_id is distinct from new.user_id then
      raise exception 'Parent category must belong to the same user';
    end if;

    if parent.parent_category is not null then
      raise exception 'Categories are only one level deep';
    end if;

    if parent.category_type is distinct from new.category_type then
      raise exception 'A child category must use the same type as its parent';
    end if;
  end if;

  return new;
end;
$$;

create or replace function public.categories_sync_children()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.category_type is distinct from old.category_type then
    update public.categories
    set category_type = new.category_type
    where parent_category = new.id
      and category_type is distinct from new.category_type;
  end if;
  return null;
end;
$$;

create or replace function public.debt_normalize()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.counterparty := btrim(new.counterparty);
  if new.notes is not null then
    new.notes := nullif(btrim(new.notes), '');
  end if;
  return new;
end;
$$;

create or replace function public.position_normalize()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.name := btrim(new.name);
  if new.notes is not null then
    new.notes := nullif(btrim(new.notes), '');
  end if;
  return new;
end;
$$;

create or replace function public.budget_validate()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  category_user uuid;
  category_parent bigint;
begin
  select user_id, parent_category
  into category_user, category_parent
  from public.categories
  where id = new.category_id;

  if category_user is null or category_user is distinct from new.user_id then
    raise exception 'Budget category must belong to the same user';
  end if;

  if category_parent is not null then
    raise exception 'Budgets can only be set on a parent category';
  end if;

  return new;
end;
$$;

create or replace function public.transaction_validate()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  category_user uuid;
  category_kind public.category_type;
  debt_user uuid;
  position_user uuid;
begin
  if new.description is not null then
    new.description := nullif(btrim(new.description), '');
  end if;

  if new.category_id is not null then
    select user_id, category_type
    into category_user, category_kind
    from public.categories
    where id = new.category_id;

    if category_user is null or category_user is distinct from new.user_id then
      raise exception 'Transaction category must belong to the same user';
    end if;

    if category_kind = 'income' and new.direction <> 'inflow' then
      raise exception 'Income categories only accept inflow transactions';
    end if;

    if category_kind = 'expense' and new.direction <> 'outflow' then
      raise exception 'Expense categories only accept outflow transactions';
    end if;
  end if;

  if new.debt_id is not null then
    select user_id into debt_user
    from public.debt
    where id = new.debt_id;

    if debt_user is null or debt_user is distinct from new.user_id then
      raise exception 'Transaction debt must belong to the same user';
    end if;
  end if;

  if new.position_id is not null then
    select user_id into position_user
    from public.position
    where id = new.position_id;

    if position_user is null or position_user is distinct from new.user_id then
      raise exception 'Transaction position must belong to the same user';
    end if;
  end if;

  return new;
end;
$$;

create trigger categories_touch_updated_at
  before insert or update on public.categories
  for each row execute function public.touch_updated_at();

create trigger categories_reject_user_change
  before update on public.categories
  for each row execute function public.reject_user_id_change();

create trigger categories_validate
  before insert or update on public.categories
  for each row execute function public.categories_validate();

create trigger categories_sync_children
  after update of category_type on public.categories
  for each row execute function public.categories_sync_children();

create trigger budget_touch_updated_at
  before insert or update on public.budget
  for each row execute function public.touch_updated_at();

create trigger budget_reject_user_change
  before update on public.budget
  for each row execute function public.reject_user_id_change();

create trigger budget_validate
  before insert or update on public.budget
  for each row execute function public.budget_validate();

create trigger debt_normalize
  before insert or update on public.debt
  for each row execute function public.debt_normalize();

create trigger debt_touch_updated_at
  before insert or update on public.debt
  for each row execute function public.touch_updated_at();

create trigger debt_reject_user_change
  before update on public.debt
  for each row execute function public.reject_user_id_change();

create trigger position_normalize
  before insert or update on public.position
  for each row execute function public.position_normalize();

create trigger position_touch_updated_at
  before insert or update on public.position
  for each row execute function public.touch_updated_at();

create trigger position_reject_user_change
  before update on public.position
  for each row execute function public.reject_user_id_change();

create trigger transaction_touch_updated_at
  before insert or update on public.transaction
  for each row execute function public.touch_updated_at();

create trigger transaction_reject_user_change
  before update on public.transaction
  for each row execute function public.reject_user_id_change();

create trigger transaction_validate
  before insert or update on public.transaction
  for each row execute function public.transaction_validate();

-- ---------------------------------------------------------------------------
-- Read model
-- security_invoker makes the caller's RLS on the base tables apply.
-- ---------------------------------------------------------------------------

create view public.transactions_with_ref
with (security_invoker = true) as
select
  t.id as transaction_id,
  t.user_id,
  t.amount,
  t.direction,
  t.transaction_date,
  t.description,
  t.category_id,
  c.category_name,
  c.category_type,
  c.parent_category as parent_category_id,
  t.debt_id,
  d.counterparty,
  d.debt_type,
  t.position_id,
  p.name as position_name,
  p.kind as position_kind,
  case
    when t.debt_id is not null then 'debt'
    when t.position_id is not null then 'position'
    else 'category'
  end as transaction_type,
  nullif(
    concat_ws(' ', t.description, c.category_name, d.counterparty, p.name),
    ''
  ) as search_text
from public.transaction as t
left join public.categories as c on c.id = t.category_id
left join public.debt as d on d.id = t.debt_id
left join public.position as p on p.id = t.position_id;

-- ---------------------------------------------------------------------------
-- Ownership helpers used by RLS.
-- security definer avoids recursive policy checks on the same table.
-- ---------------------------------------------------------------------------

create or replace function public.category_owned_by_current_user(target_id bigint)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.categories
    where id = target_id
      and user_id = (select auth.uid())
  );
$$;

create or replace function public.debt_owned_by_current_user(target_id bigint)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.debt
    where id = target_id
      and user_id = (select auth.uid())
  );
$$;

create or replace function public.position_owned_by_current_user(target_id bigint)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.position
    where id = target_id
      and user_id = (select auth.uid())
  );
$$;

revoke all on function public.touch_updated_at() from public, anon, authenticated;
revoke all on function public.reject_user_id_change() from public, anon, authenticated;
revoke all on function public.categories_validate() from public, anon, authenticated;
revoke all on function public.categories_sync_children() from public, anon, authenticated;
revoke all on function public.debt_normalize() from public, anon, authenticated;
revoke all on function public.position_normalize() from public, anon, authenticated;
revoke all on function public.budget_validate() from public, anon, authenticated;
revoke all on function public.transaction_validate() from public, anon, authenticated;
revoke all on function public.category_owned_by_current_user(bigint) from public, anon;
revoke all on function public.debt_owned_by_current_user(bigint) from public, anon;
revoke all on function public.position_owned_by_current_user(bigint) from public, anon;

grant execute on function public.category_owned_by_current_user(bigint) to authenticated;
grant execute on function public.debt_owned_by_current_user(bigint) to authenticated;
grant execute on function public.position_owned_by_current_user(bigint) to authenticated;

-- ---------------------------------------------------------------------------
-- Row level security
-- ---------------------------------------------------------------------------

alter table public.categories enable row level security;
alter table public.budget enable row level security;
alter table public.debt enable row level security;
alter table public.position enable row level security;
alter table public.transaction enable row level security;

alter table public.categories force row level security;
alter table public.budget force row level security;
alter table public.debt force row level security;
alter table public.position force row level security;
alter table public.transaction force row level security;

create policy "categories_select_own"
  on public.categories
  for select
  to authenticated
  using (user_id = (select auth.uid()));

create policy "categories_insert_own"
  on public.categories
  for insert
  to authenticated
  with check (
    user_id = (select auth.uid())
    and (
      parent_category is null
      or public.category_owned_by_current_user(parent_category)
    )
  );

create policy "categories_update_own"
  on public.categories
  for update
  to authenticated
  using (user_id = (select auth.uid()))
  with check (
    user_id = (select auth.uid())
    and (
      parent_category is null
      or public.category_owned_by_current_user(parent_category)
    )
  );

create policy "categories_delete_own"
  on public.categories
  for delete
  to authenticated
  using (user_id = (select auth.uid()));

create policy "budget_select_own"
  on public.budget
  for select
  to authenticated
  using (user_id = (select auth.uid()));

create policy "budget_insert_own"
  on public.budget
  for insert
  to authenticated
  with check (
    user_id = (select auth.uid())
    and public.category_owned_by_current_user(category_id)
  );

create policy "budget_update_own"
  on public.budget
  for update
  to authenticated
  using (user_id = (select auth.uid()))
  with check (
    user_id = (select auth.uid())
    and public.category_owned_by_current_user(category_id)
  );

create policy "budget_delete_own"
  on public.budget
  for delete
  to authenticated
  using (user_id = (select auth.uid()));

create policy "debt_select_own"
  on public.debt
  for select
  to authenticated
  using (user_id = (select auth.uid()));

create policy "debt_insert_own"
  on public.debt
  for insert
  to authenticated
  with check (user_id = (select auth.uid()));

create policy "debt_update_own"
  on public.debt
  for update
  to authenticated
  using (user_id = (select auth.uid()))
  with check (user_id = (select auth.uid()));

create policy "debt_delete_own"
  on public.debt
  for delete
  to authenticated
  using (user_id = (select auth.uid()));

create policy "position_select_own"
  on public.position
  for select
  to authenticated
  using (user_id = (select auth.uid()));

create policy "position_insert_own"
  on public.position
  for insert
  to authenticated
  with check (user_id = (select auth.uid()));

create policy "position_update_own"
  on public.position
  for update
  to authenticated
  using (user_id = (select auth.uid()))
  with check (user_id = (select auth.uid()));

create policy "position_delete_own"
  on public.position
  for delete
  to authenticated
  using (user_id = (select auth.uid()));

create policy "transaction_select_own"
  on public.transaction
  for select
  to authenticated
  using (user_id = (select auth.uid()));

create policy "transaction_insert_own"
  on public.transaction
  for insert
  to authenticated
  with check (
    user_id = (select auth.uid())
    and (
      (
        category_id is not null
        and debt_id is null
        and position_id is null
        and public.category_owned_by_current_user(category_id)
      )
      or (
        debt_id is not null
        and category_id is null
        and position_id is null
        and public.debt_owned_by_current_user(debt_id)
      )
      or (
        position_id is not null
        and category_id is null
        and debt_id is null
        and public.position_owned_by_current_user(position_id)
      )
    )
  );

create policy "transaction_update_own"
  on public.transaction
  for update
  to authenticated
  using (user_id = (select auth.uid()))
  with check (
    user_id = (select auth.uid())
    and (
      (
        category_id is not null
        and debt_id is null
        and position_id is null
        and public.category_owned_by_current_user(category_id)
      )
      or (
        debt_id is not null
        and category_id is null
        and position_id is null
        and public.debt_owned_by_current_user(debt_id)
      )
      or (
        position_id is not null
        and category_id is null
        and debt_id is null
        and public.position_owned_by_current_user(position_id)
      )
    )
  );

create policy "transaction_delete_own"
  on public.transaction
  for delete
  to authenticated
  using (user_id = (select auth.uid()));

-- ---------------------------------------------------------------------------
-- Privileges
-- anon has no access. authenticated talks to the API. service_role bypasses RLS.
-- ---------------------------------------------------------------------------

revoke all on table public.categories from public, anon;
revoke all on table public.budget from public, anon;
revoke all on table public.debt from public, anon;
revoke all on table public.position from public, anon;
revoke all on table public.transaction from public, anon;
revoke all on table public.transactions_with_ref from public, anon;

grant select, insert, update, delete on table public.categories to authenticated;
grant select, insert, update, delete on table public.budget to authenticated;
grant select, insert, update, delete on table public.debt to authenticated;
grant select, insert, update, delete on table public.position to authenticated;
grant select, insert, update, delete on table public.transaction to authenticated;
grant select on table public.transactions_with_ref to authenticated;

grant all on table public.categories to service_role;
grant all on table public.budget to service_role;
grant all on table public.debt to service_role;
grant all on table public.position to service_role;
grant all on table public.transaction to service_role;
grant select on table public.transactions_with_ref to service_role;

grant usage, select on all sequences in schema public to authenticated, service_role;
